apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-assesment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-assesment
  template:
    metadata:
      labels:
        app: golang-assesment
    spec:
      containers:
      - name: golang-assesment
        image: golang-assesment:latest
        ports:
        - containerPort: 8080
