apiVersion: v1
kind: Service
metadata:
  name: golang-assesment-service
spec:
  type: NodePort
  selector:
    app: golang-assesment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
